export const FootballClubNames = {
    england: [
        'Liverpool',
        'Brentford',
        'Arsenal',
        'Leeds United',
        'Manchester United',
        'Manchester City',
        'Chelsea',
        'Everton',
    ],
    hungary: [
        'Ferencvárosi TC',
        'Kisvárda',
        'Gyirmót',
        'MTK Budapest',
        'Honvéd FC',
        'Debreceni VSC',
        'Paks',
        'Mezőkövesd',
        'Újpest',
        'Puskás Akadémia',
        'Zalaegerszeg',
        'MOL Fehérvár FC',
    ],
};
