export interface Names {
    hu: LocaleNames;
}

export interface LocaleNames {
    firstNamesMale: string[];
    firstNamesFemale: string[];
    secondNames: string[];
}

const FIRST_NAMES_MALE_HU = [
    'Balázs',
    'Tibor',
    'János',
    'Kevin',
    'Áron',
    'Bence',
    'Dávid',
    'Zsolt',
    'Máté',
    'Tamás',
    'Péter',
    'Patrik',
    'Dániel',
    'Milán',
    'László',
    'Sándor',
    'Attila',
];
const FIRST_NAMES_FEMALE_HU = [
    'Nina',
    'Liza',
    'Gréta',
    'Blanka',
    'Petra',
    'Laura',
    'Johanna',
    'Dóra',
    'Flóra',
    'Henrietta',
    'Emma',
    'Dorka',
    'Kíra',
    'Bernadett',
    'Eszter',
    'Szilvia',
    'Éva',
    'Dalma',
    'Noémi',
    'Kitti',
    'Mónika',
];
const SECOND_NAMES_HU = [
    'Hódosi',
    'Rédei',
    'Rédai',
    'Schmid',
    'Tóvizi',
    'Kerekes',
    'Kaszás',
    'Csatári',
    'Vezendi',
    'Szántó',
    'Egri',
    'Simon',
    'Simonyi',
    'Siró',
    'Síró',
    'Gidófalvi',
    'Balázs',
    'Csomor',
    'Illés',
    'Illyés',
    'Thurzó',
    'Kerepesi',
    'Jóga',
    'Metz',
    'Beck',
    'Becker',
    'Komlósi',
    'Gócs',
    'Csicsek',
    'Könnyű',
    'Oláh',
    'Tar',
    'Kegyes',
    'Kovácsevics',
    'Szilágyi',
    'Vaskó',
    'Vaszkó',
    'Árpád',
    'Kelemen',
    'Kemencés',
    'Szántai',
    'Suhajda',
    'Hidvégi',
    'Bóka',
    'Kozma',
    'Szepesi',
    'Príbeli',
    'Szabó',
    'Kovács',
    'Molnár',
    'Kiss',
    'Kis',
    'Tóth',
    'Németh',
    'Vajda',
    'Széles',
    'Somogyi',
    'Borbély',
    'Bartha',
    'Éles',
    'Fazekas',
    'Miklós',
    'Ligetvári',
    'Lukács',
    'Lékai',
];

export const NAMES: Names = {
    hu: {
        firstNamesFemale: FIRST_NAMES_FEMALE_HU,
        firstNamesMale: FIRST_NAMES_MALE_HU,
        secondNames: SECOND_NAMES_HU,
    },
};
